### ISSUE TITLE
ModuleNotFoundError: No module named 'qc_metadata'

### ISSUE THREAD

**Issue by Millak** [arvados/bh20-seq-resource#5]
I've installed bh20-seq-resource with a combination of pip and Guix. I ran 'guix environment --ad-hoc python curl python-pycurl' to get an environment with python3 and python-pycurl and then ran 'pip3 install --user git+https://github.com/arvados/bh20-seq-resource.git@master'.  ~/.local/bin/bh20-seq-uploader --help gives me the output:

Traceback (most recent call last):
  File "/home/efraimf/.local/bin/bh20-seq-uploader", line 11, in <module>
    load_entry_point('bh20-seq-uploader==1.0.20200410122633', 'console_scripts', 'bh20-seq-uploader')()
  File "/gnu/store/mpzj907020y44yvi9gyzrmgs409xwkw9-profile/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/gnu/store/mpzj907020y44yvi9gyzrmgs409xwkw9-profile/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/gnu/store/mpzj907020y44yvi9gyzrmgs409xwkw9-profile/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/gnu/store/mpzj907020y44yvi9gyzrmgs409xwkw9-profile/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/efraimf/.local/lib/python3.7/site-packages/bh20sequploader/main.py", line 9, in <module>
    import qc_metadata
ModuleNotFoundError: No module named 'qc_metadata'

**Comment by uniqueg** [comment]
I've seen this, too. Thought it's probably just a placeholder for future work, because I haven't found such a library and the use of a module as a function doesn't make sense. Anyway, commenting the import statement and the 3 lines of dependent code in `bh20sequploader/main.py` works for now.

**Comment by pjotrp** [comment]
@Millak , can you check the GNU Guix instructions:

https://github.com/arvados/bh20-seq-resource/blob/master/doc/INSTALL.md
